nome = str(input('Qual é o seu nome: ')).strip()
n = nome.split()
print('Muito prazer {}'.format(nome))
print('Seu primeiro nome é {}'.format(n [0]))
print('Seu ultimo nome é {}'.format(n [len(n)-1]))
