nome = str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
maiusculo = nome.upper()
minusculo = nome.lower()
quantidade = len(nome) - nome.count(' ')
primeiro = nome.find(' ')
separa = nome.split()
print('Seu nome em maiusculo é: {}'.format(maiusculo))
print('Seu nome em minusculo é: {}'.format(minusculo))
print('Seu nome tem {} letras'.format(quantidade))
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], primeiro))
